from __future__ import annotations

from backend.app.core.domain_schema import EntitySpec, FieldSpec, RelationshipSpec


ENTITY_SPECS: tuple[EntitySpec, ...] = (
    EntitySpec(
        class_name="CustomerProfile",
        redis_key_template="airline_support_customer_profile:{customer_id}",
        file_name="customer_profiles.jsonl",
        id_field="customer_id",
        fields=(
            FieldSpec("customer_id", "str", "Public-safe demo customer identifier", is_key_component=True),
            FieldSpec("travel_id", "str", "Traveller profile identifier", index="tag", no_stem=True),
            FieldSpec("display_name", "str", "Traveller display name", index="text", weight=2.0),
            FieldSpec("masked_loyalty_number", "str", "Masked loyalty number", index="tag", no_stem=True),
            FieldSpec("loyalty_tier", "str", "Current loyalty tier", index="tag"),
            FieldSpec("preferred_language", "str", "Preferred language for service", index="tag"),
            FieldSpec("email", "str", "Read-only email on file", index="text", weight=1.4, no_stem=True),
            FieldSpec("consents", "str", "Summary of communication and service consents", index="text"),
        ),
        relationships=(
            RelationshipSpec("bookings", "Bookings belonging to this traveller", "customer_id", "list[Booking]"),
            RelationshipSpec("support_cases", "Support cases opened for this traveller", "customer_id", "list[SupportCase]"),
        ),
    ),
    EntitySpec(
        class_name="Booking",
        redis_key_template="airline_support_booking:{booking_id}",
        file_name="bookings.jsonl",
        id_field="booking_id",
        fields=(
            FieldSpec("booking_id", "str", "Unique booking identifier", is_key_component=True),
            FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
            FieldSpec("booking_locator", "str", "Booking locator / PNR", index="tag", no_stem=True),
            FieldSpec("passenger_display_name", "str", "Passenger display name", index="text", weight=1.6),
            FieldSpec("trip_status", "str", "Overall trip status", index="tag"),
            FieldSpec("journey_summary", "str", "Original trip summary", index="text", weight=1.8),
            FieldSpec("current_itinerary_summary", "str", "Current itinerary summary after any changes", index="text"),
            FieldSpec("created_at", "str", "Booking creation timestamp"),
            FieldSpec("fare_family", "str", "Fare family name", index="tag"),
            FieldSpec("cabin", "str", "Cabin class", index="tag"),
            FieldSpec("disruption_state", "str", "Current disruption state", index="tag"),
        ),
        relationships=(
            RelationshipSpec("segments", "Segments belonging to this booking", "booking_id", "list[FlightSegment]"),
            RelationshipSpec(
                "operational_disruptions",
                "Operational disruption events tied to this booking",
                "booking_id",
                "list[OperationalDisruption]",
            ),
            RelationshipSpec(
                "reaccommodation_records",
                "Reaccommodation records tied to this booking",
                "booking_id",
                "list[ReaccommodationRecord]",
            ),
            RelationshipSpec("support_cases", "Support cases tied to this booking", "booking_id", "list[SupportCase]"),
        ),
    ),
    EntitySpec(
        class_name="FlightSegment",
        redis_key_template="airline_support_flight_segment:{segment_id}",
        file_name="flight_segments.jsonl",
        id_field="segment_id",
        fields=(
            FieldSpec("segment_id", "str", "Unique flight segment identifier", is_key_component=True),
            FieldSpec("booking_id", "str", "Parent booking identifier", index="tag"),
            FieldSpec("flight_number", "str", "Marketing flight number", index="tag", no_stem=True),
            FieldSpec("segment_role", "str", "original, updated, or unaffected", index="tag"),
            FieldSpec("origin_airport", "str", "Origin airport code", index="tag"),
            FieldSpec("origin_city", "str", "Origin city", index="text"),
            FieldSpec("destination_airport", "str", "Destination airport code", index="tag"),
            FieldSpec("destination_city", "str", "Destination city", index="text"),
            FieldSpec("scheduled_departure", "str", "Scheduled departure timestamp"),
            FieldSpec("estimated_departure", "str", "Current estimated departure timestamp"),
            FieldSpec("scheduled_arrival", "str", "Scheduled arrival timestamp"),
            FieldSpec("estimated_arrival", "str", "Current estimated arrival timestamp"),
            FieldSpec("operating_status", "str", "Current segment operating status", index="tag"),
            FieldSpec("terminal", "str | None", "Departure terminal if known"),
            FieldSpec("gate", "str | None", "Departure gate if assigned close to departure"),
            FieldSpec("cabin", "str", "Cabin on the segment", index="tag"),
            FieldSpec("status_note", "str", "Short traveller-facing status note", index="text"),
        ),
        relationships=(
            RelationshipSpec("booking", "Booking containing this segment", "booking_id", "Booking"),
        ),
    ),
    EntitySpec(
        class_name="OperationalDisruption",
        redis_key_template="airline_support_operational_disruption:{operational_disruption_id}",
        file_name="operational_disruptions.jsonl",
        id_field="operational_disruption_id",
        fields=(
            FieldSpec(
                "operational_disruption_id",
                "str",
                "Unique operational disruption identifier",
                is_key_component=True,
            ),
            FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
            FieldSpec("booking_id", "str", "Affected booking identifier", index="tag"),
            FieldSpec("affected_segment_id", "str", "Cancelled or delayed segment identifier", index="tag"),
            FieldSpec("disruption_type", "str", "Type of disruption", index="tag"),
            FieldSpec("operational_reason", "str", "Operational cause summary", index="text"),
            FieldSpec("impact_status", "str", "Traveller-visible impact status", index="tag"),
            FieldSpec("recorded_at", "str", "Timestamp when the disruption was recorded"),
            FieldSpec("source_system", "str", "Source operational system or feed", index="tag"),
        ),
        relationships=(
            RelationshipSpec("booking", "Booking tied to this disruption", "booking_id", "Booking"),
            RelationshipSpec("affected_segment", "Affected segment", "affected_segment_id", "FlightSegment"),
        ),
    ),
    EntitySpec(
        class_name="ReaccommodationRecord",
        redis_key_template="airline_support_reaccommodation_record:{reaccommodation_record_id}",
        file_name="reaccommodation_records.jsonl",
        id_field="reaccommodation_record_id",
        fields=(
            FieldSpec(
                "reaccommodation_record_id",
                "str",
                "Unique reaccommodation identifier",
                is_key_component=True,
            ),
            FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
            FieldSpec("booking_id", "str", "Booking identifier", index="tag"),
            FieldSpec("original_segment_id", "str", "Original affected segment identifier", index="tag"),
            FieldSpec("replacement_segment_id", "str", "Replacement segment identifier", index="tag"),
            FieldSpec("reaccommodation_status", "str", "Reaccommodation status", index="tag"),
            FieldSpec("action_source", "str", "Automatic or agent-driven reassignment source", index="tag"),
            FieldSpec("reaccommodated_at", "str", "Timestamp when the reassignment was applied"),
            FieldSpec("protection_reason", "str", "Why the reassignment was created", index="text"),
        ),
        relationships=(
            RelationshipSpec("booking", "Booking tied to this reaccommodation", "booking_id", "Booking"),
            RelationshipSpec(
                "original_segment",
                "Original disrupted segment",
                "original_segment_id",
                "FlightSegment",
            ),
            RelationshipSpec(
                "replacement_segment",
                "Replacement segment assigned to the traveller",
                "replacement_segment_id",
                "FlightSegment",
            ),
        ),
    ),
    EntitySpec(
        class_name="SupportCase",
        redis_key_template="airline_support_support_case:{support_case_id}",
        file_name="support_cases.jsonl",
        id_field="support_case_id",
        fields=(
            FieldSpec("support_case_id", "str", "Unique support case identifier", is_key_component=True),
            FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
            FieldSpec("booking_id", "str", "Related booking identifier", index="tag"),
            FieldSpec("case_type", "str", "Support case type", index="tag"),
            FieldSpec("status", "str", "Support case status", index="tag"),
            FieldSpec("opened_at", "str", "Case creation timestamp"),
            FieldSpec("channel", "str", "Channel used to open the case", index="tag"),
            FieldSpec("summary", "str", "Short support summary", index="text"),
            FieldSpec("latest_note", "str", "Most recent case note", index="text"),
        ),
        relationships=(
            RelationshipSpec("booking", "Booking tied to this support case", "booking_id", "Booking"),
        ),
    ),
    EntitySpec(
        class_name="TravelPolicyDoc",
        redis_key_template="airline_support_travel_policy_doc:{doc_id}",
        file_name="travel_policy_docs.jsonl",
        id_field="doc_id",
        fields=(
            FieldSpec("doc_id", "str", "Unique policy document identifier", is_key_component=True),
            FieldSpec("category", "str", "Policy topic category", index="tag"),
            FieldSpec("title", "str", "Policy document title", index="text", weight=2.0),
            FieldSpec("content", "str", "Policy document content", index="text"),
            FieldSpec(
                "content_embedding",
                "list[float]",
                "Vector embedding for the document content",
                index="vector",
                vector_dim=1536,
                distance_metric="cosine",
            ),
        ),
    ),
)
