"""LangGraph ReAct agent for the Reddish delivery demo.

Uses ``create_react_agent`` to build a proper tool-calling loop where the LLM
decides which tools to call, inspects results, and decides what to do next.

Tools come from two sources:
  1. **Internal tools** — get_current_user_id, get_current_time, dataset_overview
  2. **MCP tools** — auto-generated by Context Surfaces (filter_*, search_*, etc.)
"""

from __future__ import annotations

import json
import logging
import warnings
from typing import Any, Optional

from langchain_core.tools import StructuredTool
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.redis.aio import AsyncRedisSaver
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field, create_model

from backend.app.context_surface_service import ContextSurfaceService
from backend.app.internal_tools import InternalToolService
from backend.app.redis_connection import build_redis_url
from backend.app.settings import Settings

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

warnings.filterwarnings("ignore", category=DeprecationWarning)
log = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are the Reddish food-delivery support assistant.

═══ AVAILABLE TOOLS ═══

Internal tools (instant, local):
  • get_current_user_id — returns the signed-in customer's ID, name, and email.
    Call this FIRST on every new question to identify who you're helping.
  • get_current_time — returns the current UTC timestamp (ISO 8601).
    Call this whenever you need to compare against order timestamps.
  • dataset_overview — returns counts of all entities in the system.

Context Surface tools (query Redis via MCP):
  • filter_order_by_customer_id — get all orders for a customer.
  • filter_orderitem_by_order_id — get line items (name, qty, price, mods) for an order.
  • filter_deliveryevent_by_order_id — get the full delivery timeline for an order.
  • filter_driver_by_active_order_id — find the driver assigned to a specific order.
    The driver record includes a `status_update` field with their real-time message.
  • filter_payment_by_order_id — get the payment breakdown for an order.
  • filter_payment_by_customer_id — get all payments for a customer.
  • filter_supportticket_by_customer_id — get past support tickets for a customer.
  • search_policy_by_text — full-text search over company policies.

═══ CRITICAL RULES ═══

1. ALWAYS FETCH FRESH DATA. Never rely on tool results from earlier in the
   conversation — data changes in real time. If you need order status, driver
   location, or current time, call the tool again NOW.

2. ALWAYS CALL TOOLS before answering data questions. Never guess or say
   "I don't have that information" if a tool exists that can answer it.

3. USE SHORT SEARCH QUERIES. The policy search uses AND matching.
   Good: "late delivery", "refund", "cancellation", "membership"
   Bad: "late delivery compensation policy for delayed orders"

═══ COMMON WORKFLOWS ═══

Late / delayed order:
  1. get_current_user_id → identify customer
  2. filter_order_by_customer_id → find the active/in-transit order
  3. get_current_time → calculate how late it is
  4. filter_deliveryevent_by_order_id → show the full timeline (where the delay happened)
  5. filter_driver_by_active_order_id → get driver status + their status_update message
  6. filter_payment_by_order_id → show what was charged
  7. search_policy_by_text("late delivery") → cite compensation rules

Payment / charges / refund:
  1. get_current_user_id → identify customer
  2. filter_order_by_customer_id → find the order
  3. filter_payment_by_order_id → get full breakdown (subtotal, fees, tip, discount, total)
  4. search_policy_by_text("refund") → cite refund eligibility

Order items / missing item:
  1. get_current_user_id → identify customer
  2. filter_order_by_customer_id → find the order
  3. filter_orderitem_by_order_id → list every item with price and modifications

═══ RESPONSE STYLE ═══

• Be concise, friendly, and specific. Use the customer's first name.
• Reference real data: order IDs, driver names, exact timestamps, dollar amounts.
• When citing policy, quote the specific rule and threshold (e.g., "delays over 30 minutes qualify for a full delivery fee refund").
"""


def _build_prompt(state: dict) -> list:
    """Build the message list for the LLM, trimming stale tool results.

    The Redis checkpointer stores the full history including tool call/result
    messages from every previous turn. Passing all of that to the LLM would
    mean it relies on stale data instead of calling tools again.

    Strategy:
      - Always include the system prompt.
      - For the CURRENT turn (latest user message onward): keep everything
        including tool calls and results — the agent needs these to reason.
      - For PREVIOUS turns: keep only human and AI text messages.
        Strip tool calls and tool results so the LLM knows what was discussed
        but must re-fetch data for current questions.
    """
    messages = state.get("messages", [])
    if not messages:
        return [SystemMessage(content=SYSTEM_PROMPT)]

    # Find the index of the last HumanMessage — that's where the current turn starts
    current_turn_start = 0
    for i in range(len(messages) - 1, -1, -1):
        if isinstance(messages[i], HumanMessage):
            current_turn_start = i
            break

    result: list = [SystemMessage(content=SYSTEM_PROMPT)]

    for msg in messages[:current_turn_start]:
        if isinstance(msg, HumanMessage):
            result.append(msg)
        elif isinstance(msg, AIMessage) and msg.content and not msg.tool_calls:
            result.append(msg)

    for msg in messages[current_turn_start:]:
        result.append(msg)

    return result


def _make_internal_tools(service: InternalToolService) -> list[StructuredTool]:
    """Wrap internal tools as LangChain StructuredTool instances."""
    tools: list[StructuredTool] = []

    def _make_fn(name: str):
        def fn(**kwargs: Any) -> str:
            result = service.execute(name, kwargs)
            return json.dumps(result, default=str)
        return fn

    for defn in service.definitions:
        schema = defn.input_schema or {"type": "object", "properties": {}}
        args_model = _pydantic_model_from_json_schema(defn.name, schema)
        tools.append(StructuredTool(
            name=defn.name,
            description=defn.description,
            func=_make_fn(defn.name),
            args_schema=args_model,
        ))
    return tools


JSON_TYPE_MAP: dict[str, type] = {
    "string": str,
    "integer": int,
    "number": float,
    "boolean": bool,
}


def _pydantic_model_from_json_schema(name: str, schema: dict) -> type[BaseModel]:
    """Build a Pydantic model from a JSON Schema ``properties`` dict."""
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    fields: dict[str, Any] = {}
    for prop_name, prop_def in props.items():
        py_type = JSON_TYPE_MAP.get(prop_def.get("type", "string"), str)
        desc = prop_def.get("description", "")
        if prop_name in required:
            fields[prop_name] = (py_type, Field(description=desc))
        else:
            default = prop_def.get("default")
            fields[prop_name] = (Optional[py_type], Field(default=default, description=desc))
    return create_model(f"Schema_{name}", **fields)


def _make_mcp_tool(
    tool_def: dict[str, Any],
    cs_service: ContextSurfaceService,
) -> StructuredTool:
    """Wrap a single MCP tool definition as a LangChain StructuredTool."""
    name = tool_def["name"]
    description = tool_def.get("description", name)
    input_schema = tool_def.get("inputSchema", {"type": "object", "properties": {}})
    args_model = _pydantic_model_from_json_schema(name, input_schema)

    async def fn(**kwargs: Any) -> str:
        # Strip None values — MCP server rejects null for optional numeric params
        clean_args = {k: v for k, v in kwargs.items() if v is not None}
        try:
            result = await cs_service.call_tool(name, clean_args)
            return json.dumps(result or {}, default=str)
        except Exception as exc:
            log.exception("MCP tool %s failed", name)
            return json.dumps({"error": str(exc)})

    return StructuredTool(
        name=name,
        description=description,
        func=lambda **kw: "",  # sync stub — we use coroutine
        coroutine=fn,
        args_schema=args_model,
    )


async def build_mcp_tools(cs_service: ContextSurfaceService) -> list[StructuredTool]:
    """Fetch MCP tool definitions and wrap them as LangChain tools."""
    mcp_defs = await cs_service.list_tools()
    return [_make_mcp_tool(t, cs_service) for t in mcp_defs]


async def create_checkpointer(settings: Settings) -> AsyncRedisSaver:
    """Create an async Redis checkpointer for LangGraph conversation state."""
    redis_url = build_redis_url(settings)
    checkpointer = AsyncRedisSaver(
        redis_url=redis_url,
        checkpoint_prefix="reddash:checkpoint",
        checkpoint_write_prefix="reddash:checkpoint_write",
    )
    await checkpointer.asetup()
    log.info("Redis checkpointer connected at %s:%d", settings.redis_host, settings.redis_port)
    return checkpointer


async def create_agent(
    settings: Settings,
    internal_tools: InternalToolService,
    cs_service: ContextSurfaceService,
    checkpointer: AsyncRedisSaver | None = None,
):
    """Create a LangGraph ReAct agent with all available tools and Redis checkpointer."""
    model = ChatOpenAI(
        model=settings.openai_chat_model,
        temperature=0.2,
        api_key=settings.openai_api_key,
    )

    tools = _make_internal_tools(internal_tools)
    mcp_tools = await build_mcp_tools(cs_service)
    tools.extend(mcp_tools)

    log.info("Creating LangGraph agent with %d tools (%d internal, %d MCP), checkpointer=%s",
             len(tools), len(tools) - len(mcp_tools), len(mcp_tools),
             "redis" if checkpointer else "none")

    return create_react_agent(model, tools, prompt=_build_prompt, checkpointer=checkpointer)

