"""LangGraph ReAct agent for the active demo domain.

Uses ``create_react_agent`` to build a proper tool-calling loop where the LLM
decides which tools to call, inspects results, and decides what to do next.

Tools come from two sources:
  1. **Internal tools** — domain-defined local helpers
  2. **MCP tools** — auto-generated by Context Surfaces (filter_*, search_*, etc.)
"""

from __future__ import annotations

import json
import logging
import warnings
from typing import Any, Callable, Optional

from langchain_core.tools import StructuredTool
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.redis.aio import AsyncRedisSaver
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel, Field, create_model

from backend.app.context_surface_service import ContextSurfaceService
from backend.app.core.domain_loader import get_active_domain
from backend.app.internal_tools import InternalToolService, domain_runtime_config
from backend.app.redis_connection import build_redis_url
from backend.app.settings import Settings

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage

warnings.filterwarnings("ignore", category=DeprecationWarning)
log = logging.getLogger(__name__)


def _build_prompt_factory(system_prompt: str) -> Callable[[dict], list]:
    """Build the message list for the LLM, trimming stale tool results.

    The Redis checkpointer stores the full history including tool call/result
    messages from every previous turn. Passing all of that to the LLM would
    mean it relies on stale data instead of calling tools again.

    Strategy:
      - Always include the system prompt.
      - For the CURRENT turn (latest user message onward): keep everything
        including tool calls and results — the agent needs these to reason.
      - For PREVIOUS turns: keep only human and AI text messages.
        Strip tool calls and tool results so the LLM knows what was discussed
        but must re-fetch data for current questions.
    """
    def _build_prompt(state: dict) -> list:
        messages = state.get("messages", [])
        if not messages:
            return [SystemMessage(content=system_prompt)]

        current_turn_start = 0
        for i in range(len(messages) - 1, -1, -1):
            if isinstance(messages[i], HumanMessage):
                current_turn_start = i
                break

        result: list = [SystemMessage(content=system_prompt)]

        for msg in messages[:current_turn_start]:
            if isinstance(msg, HumanMessage):
                result.append(msg)
            elif isinstance(msg, AIMessage) and msg.content and not msg.tool_calls:
                result.append(msg)

        for msg in messages[current_turn_start:]:
            result.append(msg)

        return result

    return _build_prompt


def _message_content(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        parts: list[str] = []
        for item in value:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                text = item.get("text")
                if text:
                    parts.append(str(text))
        return "\n".join(parts)
    return str(value)


def _serialize_verifier_context(messages: list[Any]) -> str:
    latest_human_idx = 0
    for i in range(len(messages) - 1, -1, -1):
        if isinstance(messages[i], HumanMessage):
            latest_human_idx = i
            break

    prior_messages: list[Any] = []
    for msg in messages[:latest_human_idx]:
        if isinstance(msg, HumanMessage):
            prior_messages.append(msg)
        elif isinstance(msg, AIMessage) and msg.content and not msg.tool_calls:
            prior_messages.append(msg)
    relevant = prior_messages[-4:] + messages[latest_human_idx:]

    lines: list[str] = []
    for msg in relevant:
        if isinstance(msg, HumanMessage):
            lines.append(f"User: {_message_content(msg.content)}")
        elif isinstance(msg, AIMessage):
            if msg.tool_calls:
                tool_names = ", ".join(call.get("name", "") for call in msg.tool_calls)
                lines.append(f"Assistant tool plan: {tool_names}")
            else:
                lines.append(f"Assistant: {_message_content(msg.content)}")
        elif isinstance(msg, ToolMessage):
            tool_output = _message_content(msg.content)
            if len(tool_output) > 1600:
                tool_output = tool_output[:1600] + "..."
            lines.append(f"Tool {msg.name}: {tool_output}")
    return "\n\n".join(lines)


def _build_post_model_hook(
    model: ChatOpenAI,
    *,
    domain: Any,
    lightweight_model_name: str,
    runtime_config: dict[str, Any],
) -> Callable[[dict], Any]:
    verifier_model = ChatOpenAI(
        model=lightweight_model_name
        or getattr(model, "model_name", None)
        or getattr(model, "model", None),
        temperature=0.2,
        api_key=getattr(model, "openai_api_key", None) or getattr(model, "api_key", None),
    )
    domain_guidance = ""
    if hasattr(domain, "build_answer_verifier_prompt"):
        domain_guidance = str(domain.build_answer_verifier_prompt(runtime_config=runtime_config) or "").strip()

    async def _post_model_hook(state: dict) -> dict[str, list[AIMessage]]:
        messages = state.get("messages", [])
        if not messages:
            return {}

        last_ai: AIMessage | None = None
        for msg in reversed(messages):
            if isinstance(msg, AIMessage):
                last_ai = msg
                break
        if last_ai is None or last_ai.tool_calls or not _message_content(last_ai.content).strip():
            return {}

        current_turn_has_tool_data = False
        for msg in reversed(messages):
            if isinstance(msg, HumanMessage):
                break
            if isinstance(msg, ToolMessage):
                current_turn_has_tool_data = True
                break
        if not current_turn_has_tool_data:
            return {}

        verifier_prompt = _serialize_verifier_context(messages)
        response = await verifier_model.ainvoke(
            [
                SystemMessage(
                    content=(
                        "You are a lightweight answer verifier for a tool-using assistant. "
                        "Revise the draft answer only if needed to make it better grounded in the recent conversation "
                        "and tool results. Resolve references like 'that' or 'those' using recent turns. "
                        "Remove unsupported claims. Do not claim stock, pickup timing, or delivery status unless the tool "
                        "results in context support it. "
                        "If the domain guidance below is relevant, follow it as an additional grounding constraint.\n\n"
                        f"DOMAIN-SPECIFIC VERIFIER GUIDANCE:\n{domain_guidance or 'None.'}"
                        "\n\nKeep the same concise tone and output only the final answer markdown."
                    )
                ),
                HumanMessage(
                    content=(
                        f"Conversation and tool context:\n\n{verifier_prompt}\n\n"
                        f"Draft answer:\n\n{_message_content(last_ai.content)}"
                    )
                ),
            ]
        )
        verified_content = _message_content(response.content).strip()
        if not verified_content:
            return {}
        return {"messages": [AIMessage(content=verified_content, id=last_ai.id)]}

    return _post_model_hook


def _make_internal_tools(service: InternalToolService) -> list[StructuredTool]:
    """Wrap internal tools as LangChain StructuredTool instances."""
    tools: list[StructuredTool] = []

    def _make_fn(name: str):
        def fn(**kwargs: Any) -> str:
            result = service.execute(name, kwargs)
            return json.dumps(result, default=str)
        return fn

    for defn in service.definitions:
        schema = defn.input_schema or {"type": "object", "properties": {}}
        args_model = _pydantic_model_from_json_schema(defn.name, schema)
        tools.append(StructuredTool(
            name=defn.name,
            description=defn.description,
            func=_make_fn(defn.name),
            args_schema=args_model,
        ))
    return tools


JSON_TYPE_MAP: dict[str, type] = {
    "string": str,
    "integer": int,
    "number": float,
    "boolean": bool,
}


def _pydantic_model_from_json_schema(name: str, schema: dict) -> type[BaseModel]:
    """Build a Pydantic model from a JSON Schema ``properties`` dict."""
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    fields: dict[str, Any] = {}
    for prop_name, prop_def in props.items():
        py_type = JSON_TYPE_MAP.get(prop_def.get("type", "string"), str)
        desc = prop_def.get("description", "")
        if prop_name in required:
            fields[prop_name] = (py_type, Field(description=desc))
        else:
            default = prop_def.get("default")
            fields[prop_name] = (Optional[py_type], Field(default=default, description=desc))
    return create_model(f"Schema_{name}", **fields)


def _make_mcp_tool(
    tool_def: dict[str, Any],
    cs_service: ContextSurfaceService,
) -> StructuredTool:
    """Wrap a single MCP tool definition as a LangChain StructuredTool."""
    name = tool_def["name"]
    description = tool_def.get("description", name)
    input_schema = tool_def.get("inputSchema", {"type": "object", "properties": {}})
    args_model = _pydantic_model_from_json_schema(name, input_schema)

    async def fn(**kwargs: Any) -> str:
        # Strip None values — MCP server rejects null for optional numeric params
        clean_args = {k: v for k, v in kwargs.items() if v is not None}
        try:
            result = await cs_service.call_tool(name, clean_args)
            return json.dumps(result or {}, default=str)
        except Exception as exc:
            log.exception("MCP tool %s failed", name)
            return json.dumps({"error": str(exc)})

    return StructuredTool(
        name=name,
        description=description,
        func=lambda **kw: "",  # sync stub — we use coroutine
        coroutine=fn,
        args_schema=args_model,
    )


async def build_mcp_tools(cs_service: ContextSurfaceService) -> list[StructuredTool]:
    """Fetch MCP tool definitions and wrap them as LangChain tools."""
    mcp_defs = await cs_service.list_tools()
    return [_make_mcp_tool(t, cs_service) for t in mcp_defs]


async def create_checkpointer(settings: Settings) -> AsyncRedisSaver:
    """Create an async Redis checkpointer for LangGraph conversation state."""
    redis_url = build_redis_url(settings)
    domain = get_active_domain(settings)
    checkpointer = AsyncRedisSaver(
        redis_url=redis_url,
        checkpoint_prefix=domain.manifest.namespace.checkpoint_prefix,
        checkpoint_write_prefix=domain.manifest.namespace.checkpoint_write_prefix,
    )
    await checkpointer.asetup()
    log.info("Redis checkpointer connected at %s:%d", settings.redis_host, settings.redis_port)
    return checkpointer


async def create_agent(
    settings: Settings,
    internal_tools: InternalToolService,
    cs_service: ContextSurfaceService,
    checkpointer: AsyncRedisSaver | None = None,
):
    """Create a LangGraph ReAct agent with all available tools and Redis checkpointer."""
    domain = get_active_domain(settings)
    runtime_config = domain_runtime_config(domain, settings)
    model = ChatOpenAI(
        model=settings.openai_chat_model,
        temperature=0.2,
        api_key=settings.openai_api_key,
    )

    tools = _make_internal_tools(internal_tools)
    mcp_defs = await cs_service.list_tools()
    mcp_tools = [_make_mcp_tool(t, cs_service) for t in mcp_defs]
    tools.extend(mcp_tools)
    prompt = _build_prompt_factory(domain.build_system_prompt(mcp_tools=mcp_defs, runtime_config=runtime_config))
    post_model_hook = None
    if runtime_config.get("enable_post_model_verifier", False):
        post_model_hook = _build_post_model_hook(
            model,
            domain=domain,
            lightweight_model_name=settings.openai_lightweight_model or settings.openai_chat_model,
            runtime_config=runtime_config,
        )

    log.info("Creating LangGraph agent with %d tools (%d internal, %d MCP), checkpointer=%s",
             len(tools), len(tools) - len(mcp_tools), len(mcp_tools),
             "redis" if checkpointer else "none")

    agent_kwargs: dict[str, Any] = {
        "prompt": prompt,
        "checkpointer": checkpointer,
    }
    if post_model_hook is not None:
        agent_kwargs["post_model_hook"] = post_model_hook

    return create_react_agent(
        model,
        tools,
        **agent_kwargs,
    )
