from __future__ import annotations

from backend.app.core.domain_schema import (
    EntitySpec,
    FieldSpec,
    RelationshipSpec,
    entity_by_class,
    entity_by_file,
)


ENTITY_SPECS: tuple[EntitySpec, ...] = (
    EntitySpec(
        class_name="AnalystProfile",
        redis_key_template="finance_researcher_analyst_profile:{analyst_id}",
        file_name="analyst_profiles.jsonl",
        id_field="analyst_id",
        fields=(
            FieldSpec("analyst_id", "str", "Unique analyst identifier", is_key_component=True),
            FieldSpec("name", "str", "Analyst full name", index="text", weight=2.0),
            FieldSpec("email", "str", "Analyst email", index="text", no_stem=True),
            FieldSpec("firm_name", "str", "Research firm or desk", index="text"),
            FieldSpec("role", "str", "Analyst role or title", index="text"),
            FieldSpec("watchlist_name", "str", "Named watchlist used for the demo", index="text"),
            FieldSpec("watchlist_theme", "str", "Primary coverage theme", index="tag"),
            FieldSpec("active_watchlist_count", "int", "Number of companies in the active watchlist", index="numeric", sortable=True),
            FieldSpec("as_of_date", "str", "ISO date for the analyst context snapshot"),
        ),
    ),
    EntitySpec(
        class_name="Company",
        redis_key_template="finance_researcher_company:{company_id}",
        file_name="companies.jsonl",
        id_field="company_id",
        fields=(
            FieldSpec("company_id", "str", "Unique company identifier", is_key_component=True),
            FieldSpec("ticker", "str", "Public ticker symbol", index="tag", no_stem=True),
            FieldSpec("company_name", "str", "Company legal or common name", index="text", weight=2.0),
            FieldSpec("cik", "str", "SEC CIK identifier", index="tag", no_stem=True),
            FieldSpec("sector", "str", "GICS sector", index="tag"),
            FieldSpec("subsector", "str", "GICS subsector or business line", index="tag"),
            FieldSpec("benchmark_group", "str", "Peer benchmark group", index="tag"),
            FieldSpec("exchange", "str", "Primary listing exchange", index="tag"),
            FieldSpec("headquarters_city", "str", "Company headquarters city", index="tag"),
            FieldSpec("headquarters_state", "str", "Company headquarters state", index="tag"),
            FieldSpec("watchlist_rank", "int", "Priority rank in the analyst watchlist", index="numeric", sortable=True),
            FieldSpec("website_url", "str", "Investor relations or corporate website", index="text"),
        ),
        relationships=(
            RelationshipSpec(
                "documents",
                "Research documents for this company",
                "company_id",
                "list[ResearchDocument]",
            ),
            RelationshipSpec(
                "metrics",
                "Financial metrics for this company",
                "company_id",
                "list[FinancialMetricPoint]",
            ),
            RelationshipSpec(
                "prices",
                "Price history for this company",
                "company_id",
                "list[PriceBar]",
            ),
            RelationshipSpec(
                "events",
                "Coverage events for this company",
                "company_id",
                "list[CoverageEvent]",
            ),
        ),
    ),
    EntitySpec(
        class_name="ResearchDocument",
        redis_key_template="finance_researcher_research_document:{document_id}",
        file_name="research_documents.jsonl",
        id_field="document_id",
        fields=(
            FieldSpec("document_id", "str", "Unique document identifier", is_key_component=True),
            FieldSpec("company_id", "str", "Parent company identifier", index="tag"),
            FieldSpec("ticker", "str", "Company ticker symbol", index="tag", no_stem=True),
            FieldSpec("title", "str", "Document title", index="text", weight=2.0),
            FieldSpec("source_type", "str", "Source type such as sec_filing, earnings_release, presentation, or remarks", index="tag"),
            FieldSpec("document_family", "str", "Normalized family label for the source document", index="tag"),
            FieldSpec("published_at", "str", "ISO timestamp when the source was published"),
            FieldSpec("fiscal_period", "str | None", "Fiscal period such as Q1, Q2, Q3, or FY", index="tag"),
            FieldSpec("fiscal_year", "int | None", "Fiscal year", index="numeric", sortable=True),
            FieldSpec("source_url", "str", "Canonical source URL", index="text"),
            FieldSpec("local_path", "str", "Relative path to the downloaded artifact", index="text"),
            FieldSpec("mime_type", "str", "Artifact mime type", index="tag"),
            FieldSpec("sha256", "str", "SHA-256 digest of the downloaded artifact", index="tag", no_stem=True),
        ),
        relationships=(
            RelationshipSpec("company", "Owning company", "company_id", "Company"),
            RelationshipSpec(
                "chunks",
                "Text chunks derived from this document",
                "document_id",
                "list[ResearchChunk]",
            ),
        ),
    ),
    EntitySpec(
        class_name="ResearchChunk",
        redis_key_template="finance_researcher_research_chunk:{chunk_id}",
        file_name="research_chunks.jsonl",
        id_field="chunk_id",
        fields=(
            FieldSpec("chunk_id", "str", "Unique chunk identifier", is_key_component=True),
            FieldSpec("document_id", "str", "Parent research document", index="tag"),
            FieldSpec("company_id", "str", "Parent company identifier", index="tag"),
            FieldSpec("ticker", "str", "Company ticker symbol", index="tag", no_stem=True),
            FieldSpec("section_heading", "str | None", "Section heading or subsection title", index="text"),
            FieldSpec("page_label", "str | None", "Page label, page number, or extracted section marker", index="tag"),
            FieldSpec("chunk_text", "str", "Normalized chunk text", index="text", weight=2.0),
            FieldSpec(
                "content_embedding",
                "list[float]",
                "Vector embedding of the chunk text",
                index="vector",
                vector_dim=1536,
                distance_metric="cosine",
            ),
        ),
        relationships=(
            RelationshipSpec("document", "Parent research document", "document_id", "ResearchDocument"),
            RelationshipSpec("company", "Owning company", "company_id", "Company"),
        ),
    ),
    EntitySpec(
        class_name="FinancialMetricPoint",
        redis_key_template="finance_researcher_financial_metric_point:{point_id}",
        file_name="financial_metric_points.jsonl",
        id_field="point_id",
        fields=(
            FieldSpec("point_id", "str", "Unique metric point identifier", is_key_component=True),
            FieldSpec("company_id", "str", "Parent company identifier", index="tag"),
            FieldSpec("ticker", "str", "Company ticker symbol", index="tag", no_stem=True),
            FieldSpec("metric_name", "str", "Metric name such as revenue or net_income", index="tag"),
            FieldSpec("period_type", "str", "Annual or quarterly period type", index="tag"),
            FieldSpec("fiscal_year", "int", "Fiscal year", index="numeric", sortable=True),
            FieldSpec("fiscal_period", "str | None", "Fiscal period label such as Q1, Q2, Q3, Q4, or FY", index="tag"),
            FieldSpec("period_end", "str", "ISO period end date"),
            FieldSpec("value", "float", "Metric value", index="numeric", sortable=True),
            FieldSpec("unit", "str", "Unit of measure", index="tag"),
            FieldSpec("currency", "str | None", "Currency code such as USD", index="tag"),
        ),
        relationships=(
            RelationshipSpec("company", "Owning company", "company_id", "Company"),
        ),
    ),
    EntitySpec(
        class_name="PriceBar",
        redis_key_template="finance_researcher_price_bar:{bar_id}",
        file_name="price_bars.jsonl",
        id_field="bar_id",
        fields=(
            FieldSpec("bar_id", "str", "Unique price bar identifier", is_key_component=True),
            FieldSpec("company_id", "str", "Parent company identifier", index="tag"),
            FieldSpec("ticker", "str", "Company ticker symbol", index="tag", no_stem=True),
            FieldSpec("trade_date", "str", "Trading date", index="tag"),
            FieldSpec("open", "float", "Opening price", index="numeric", sortable=True),
            FieldSpec("high", "float", "High price", index="numeric", sortable=True),
            FieldSpec("low", "float", "Low price", index="numeric", sortable=True),
            FieldSpec("close", "float", "Close price", index="numeric", sortable=True),
            FieldSpec("adj_close", "float", "Adjusted close price", index="numeric", sortable=True),
            FieldSpec("volume", "int", "Trading volume", index="numeric", sortable=True),
        ),
        relationships=(
            RelationshipSpec("company", "Owning company", "company_id", "Company"),
        ),
    ),
    EntitySpec(
        class_name="CoverageEvent",
        redis_key_template="finance_researcher_coverage_event:{event_id}",
        file_name="coverage_events.jsonl",
        id_field="event_id",
        fields=(
            FieldSpec("event_id", "str", "Unique event identifier", is_key_component=True),
            FieldSpec("company_id", "str", "Parent company identifier", index="tag"),
            FieldSpec("ticker", "str", "Company ticker symbol", index="tag", no_stem=True),
            FieldSpec("event_family", "str", "Normalized family such as filing, earnings, presentation, or price", index="tag"),
            FieldSpec("event_type", "str", "Event type such as new_filing, new_release, new_presentation, or price_move", index="tag"),
            FieldSpec("published_at", "str", "ISO timestamp of the event"),
            FieldSpec("document_id", "str | None", "Related research document", index="tag"),
            FieldSpec("headline", "str", "Short human-readable event headline", index="text", weight=2.0),
            FieldSpec("importance_score", "float", "Relative importance score", index="numeric", sortable=True),
        ),
        relationships=(
            RelationshipSpec("company", "Owning company", "company_id", "Company"),
            RelationshipSpec(
                "document",
                "Related research document",
                "document_id",
                "ResearchDocument | None",
            ),
        ),
    ),
)

ENTITY_BY_FILE = entity_by_file(ENTITY_SPECS)
ENTITY_BY_CLASS = entity_by_class(ENTITY_SPECS)
